name: Wiki Content Sync

on:
  push:
    branches:
      - main
    paths:
      - "chess/**"        # All files regarding the chess project
      - "instruction/**"  # All files regarding class topics
      - "*.*"             # Root directory README or the images it uses
  repository_dispatch:
    types: [docs]
  workflow_dispatch: 
  gollum:
  
env:
  GIT_AUTHOR_NAME: GitHub Action
  GIT_AUTHOR_EMAIL: action@github.com

jobs:
  sync-content-to-wiki:
    if: always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && github.event_name != 'gollum'
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Group Document files
        run: |
          rsync -av --exclude='.git*' --exclude='LICENSE' --include='petshop/*' --exclude='petshop/*/*' --exclude='schedule' --exclude='README.md' --exclude='instruction/template' ./ docs/
          cp README.md docs/Home.md
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@v1.0.1
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.WIKI_SYNC_SECRET }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}